{{-- 출력 없음. CSS/JS 로드 순서를 번호 접두어로 고정한다. 경로는 이 파일이 있는 layout/ 기준 상대경로라 ../ 로 스킨 루트를 거친다. --}}
@load('../css/00-tokens.css')
@load('../css/10-base.css')
@load('../css/20-layout.css')
@load('../css/30-list.css')
@load('../css/31-card.css')
@load('../css/40-read.css')
@load('../css/50-comment.css')
@load('../css/51-sticker.css')
@load('../css/60-form.css')
@load('../css/70-ui.css')
@load('../css/90-responsive.css')
@load('../js/cube.core.js', 'body')
@load('../js/cube.list.js', 'body')
@load('../js/cube.manage.js', 'body')
@load('../js/cube.action.js', 'body')
@load('../js/cube.sticker.js', 'body')
@load('../js/cube.ui.js', 'body')
